// ============================================================
//  APP.JS — Do NOT edit this file unless you're adding features.
//  It reads from content.js and builds the page automatically.
// ============================================================

document.addEventListener('DOMContentLoaded', () => {
  buildPage();
  initNavbar();
  initMobileMenu();
  initScrollReveal();
  initSmoothScroll();
  initActiveNav();
});

// =============================================
// PAGE BUILDER — Reads SITE config and renders
// =============================================
function buildPage() {
  buildMeta();
  buildHero();
  buildProducts();
  buildFeatures();
  buildAbout();
  buildContact();
  buildFooter();
}

function buildMeta() {
  const S = SITE.brand;
  document.title = S.pageTitle;
  document.querySelector('meta[name="description"]').content = S.metaDescription;
  document.querySelectorAll('.brand-name').forEach(el => {
    if (S.logo) {
      el.innerHTML = `<img src="${S.logo}" alt="${S.name}" class="brand-logo" />`;
    } else {
      el.textContent = S.name;
    }
  });
}

function buildHero() {
  const H = SITE.hero;
  const sec = document.getElementById('hero');

  document.getElementById('hero-eyebrow').textContent  = H.eyebrow;
  document.getElementById('hero-title').textContent    = H.title;
  document.getElementById('hero-subtitle').textContent = H.subtitle;

  const p = document.getElementById('hero-cta-primary');
  const s = document.getElementById('hero-cta-secondary');
  p.textContent = H.ctaPrimary.text;   p.href = H.ctaPrimary.link;
  s.textContent = H.ctaSecondary.text; s.href = H.ctaSecondary.link;

  if (H.backgroundImage) {
    sec.style.background =
      `linear-gradient(to bottom, rgba(0,0,0,0.45) 0%, rgba(0,0,0,0.35) 100%),
       url('${H.backgroundImage}') center/cover no-repeat`;
  }
}

function buildProducts() {
  const P = SITE.homeProducts;
  if (!P) return;

  document.getElementById('prod-tag').textContent   = P.sectionTag;
  document.getElementById('prod-title').textContent = P.sectionTitle;
  document.getElementById('prod-desc').textContent  = P.sectionDesc;

  const grid = document.getElementById('prod-grid');
  grid.innerHTML = P.items.map(item => `
    <div class="cat-card">
      <div class="cat-img" style="background: var(--grey-light);">
        <img src="${item.image}" alt="${item.name}" class="cat-photo"
          onerror="this.style.display='none'" />
      </div>
      ${item.badge ? `<span class="badge">${item.badge}</span>` : ''}
      <div class="cat-body">
        <h3>${item.name}</h3>
        <p>${item.description}</p>
        <div style="margin-top:12px; display:flex; align-items:center; justify-content:space-between;">
          <span style="font-weight:600; color:var(--dark); font-size:1.1rem;">${item.price}</span>
          ${item.originalPrice ? `<span style="text-decoration:line-through; color:var(--grey); font-size:0.9rem;">${item.originalPrice}</span>` : ''}
        </div>
      </div>
    </div>
  `).join('');
}

function buildFeatures() {
  const grid = document.getElementById('features-grid');
  grid.innerHTML = SITE.features.map((f, i) => `
    <div class="feature-item" id="feat-${i}">
      <div class="feature-icon">${f.icon}</div>
      <h4>${f.title}</h4>
      <p>${f.description}</p>
    </div>
  `).join('');
}

function buildAbout() {
  const A = SITE.about;
  document.getElementById('about-tag').textContent   = A.sectionTag;
  document.getElementById('about-title').textContent = A.title;
  document.getElementById('about-text').innerHTML    = A.paragraphs.map(p => `<p>${p}</p>`).join('');
  document.getElementById('about-cta').textContent   = A.ctaText;
  document.getElementById('about-cta').href          = A.ctaLink;

  // Stats cards
  document.getElementById('about-stats').innerHTML = A.stats.map((s, i) => `
    <div class="about-card ac${i+1}">
      <span>${s.value}</span>
      <strong>${s.label}</strong>
    </div>
  `).join('');

  // Values
  document.getElementById('about-values').innerHTML = A.values.map(v =>
    `<div class="value-pill">${v}</div>`
  ).join('');

  // About image
  const imgWrap = document.getElementById('about-img-wrap');
  if (A.image) {
    imgWrap.innerHTML = `<img src="${A.image}" alt="About BAG" class="about-photo" onerror="this.parentElement.innerHTML='${bagIllustrationHTML()}'" />`;
  } else {
    imgWrap.innerHTML = bagIllustrationHTML();
  }
}

function bagIllustrationHTML() {
  return `<div class="bag-illustration"><div class="bag-body"><div class="bag-handle"></div><div class="bag-clasp"></div></div></div>`;
}

function buildContact() {
  const C = SITE.contact;
  document.getElementById('contact-tag').textContent   = C.sectionTag;
  document.getElementById('contact-title').textContent = C.sectionTitle;
  document.getElementById('contact-desc').textContent  = C.sectionDesc;
  document.getElementById('contact-email').textContent   = C.email;
  document.getElementById('contact-phone').textContent   = C.phone;
  document.getElementById('contact-address').textContent = C.address;

  const ig = document.getElementById('social-instagram');
  const wa = document.getElementById('social-whatsapp');
  ig.href = C.instagram; wa.href = C.whatsapp;
}

function buildFooter() {
  const F = SITE.footer;
  document.getElementById('footer-desc').textContent      = F.description;
  document.getElementById('footer-year').textContent      = F.copyrightYear;
  document.getElementById('footer-brand-name').textContent = SITE.brand.name;
  const navBrand = document.getElementById('footer-nav-brand');
  if (SITE.brand.logo) {
    navBrand.innerHTML = `<img src="${SITE.brand.logo}" alt="${SITE.brand.name}" class="brand-logo footer-logo" />`;
  } else {
    navBrand.textContent = SITE.brand.name;
  }

  document.getElementById('footer-quick').innerHTML = F.quickLinks.map(l =>
    `<a href="${l.link}">${l.text}</a>`).join('');

  if (SITE.categories) {
    document.getElementById('footer-cat').innerHTML = SITE.categories.items.slice(0, 4).map(c =>
      `<a href="category.html?id=${c.id}">${c.name}</a>`).join('');
  } else if (SITE.homeProducts) {
    document.getElementById('footer-cat').innerHTML = SITE.homeProducts.items.slice(0, 4).map(p =>
      `<a href="#products">${p.name}</a>`).join('');
  }

  document.getElementById('footer-support').innerHTML = F.supportLinks.map(l =>
    `<a href="${l.link}">${l.text}</a>`).join('');
}

// =============================================
// INTERACTIONS
// =============================================
function initNavbar() {
  const navbar = document.getElementById('navbar');
  window.addEventListener('scroll', () => {
    navbar.classList.toggle('scrolled', window.scrollY > 60);
  });
}

function initMobileMenu() {
  const hamburger   = document.getElementById('hamburger');
  const mobileMenu  = document.getElementById('mobileMenu');
  hamburger.addEventListener('click', () => mobileMenu.classList.toggle('open'));
  document.addEventListener('click', e => {
    if (!hamburger.contains(e.target) && !mobileMenu.contains(e.target)) {
      mobileMenu.classList.remove('open');
    }
  });
}

window.closeMobile = () => document.getElementById('mobileMenu').classList.remove('open');

function initSmoothScroll() {
  document.querySelectorAll('a[href^="#"]').forEach(a => {
    const href = a.getAttribute('href');
    // Only handle pure hash anchors like "#section" — skip "#" alone and any non-hash hrefs
    if (!href || href === '#' || !href.startsWith('#')) return;
    a.addEventListener('click', e => {
      const target = document.querySelector(href);
      if (target) {
        e.preventDefault();
        window.scrollTo({ top: target.offsetTop - 80, behavior: 'smooth' });
      }
    });
  });
}

function initScrollReveal() {
  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry, i) => {
      if (entry.isIntersecting) {
        setTimeout(() => {
          entry.target.style.opacity = '1';
          entry.target.style.transform = 'translateY(0)';
        }, i * 70);
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.12, rootMargin: '0px 0px -40px 0px' });

  document.querySelectorAll('.cat-card, .feature-item, .about-content, .about-visual, .contact-item, .section-header').forEach(el => {
    el.style.cssText += 'opacity:0;transform:translateY(24px);transition:opacity 0.6s ease,transform 0.6s ease;';
    observer.observe(el);
  });
}

function initActiveNav() {
  const sections  = document.querySelectorAll('section[id]');
  const navLinks  = document.querySelectorAll('.nav-links a');
  window.addEventListener('scroll', () => {
    let current = '';
    sections.forEach(s => { if (window.scrollY >= s.offsetTop - 120) current = s.id; });
    navLinks.forEach(a => {
      a.style.color = a.getAttribute('href') === `#${current}` ? 'var(--accent)' : '';
    });
  });
}

// =============================================
// CONTACT FORM
// =============================================
window.handleSubmit = function(e) {
  e.preventDefault();
  const btn     = document.getElementById('submitBtn');
  const success = document.getElementById('formSuccess');
  btn.textContent = 'Sending…'; btn.disabled = true;
  setTimeout(() => {
    e.target.reset();
    btn.textContent = 'Send Message'; btn.disabled = false;
    success.classList.add('show');
    setTimeout(() => success.classList.remove('show'), 5000);
  }, 1200);
};
