// ============================================================
//  CATEGORY.JS — Renders the category page from content.js
//  Do NOT edit this file unless adding new features.
// ============================================================

let currentCategory = null;
let currentProducts  = [];

document.addEventListener('DOMContentLoaded', () => {
  // 1. Read ?id= from URL
  const params = new URLSearchParams(window.location.search);
  const id     = params.get('id');

  // 2. Find the matching category
  currentCategory = SITE.categories.items.find(c => c.id === id);

  if (!currentCategory) {
    // Unknown id — redirect home
    window.location.href = 'index.html#categories';
    return;
  }

  currentProducts = [...currentCategory.products];

  // 3. Build the page
  buildMeta();
  buildHero();
  buildProducts(currentProducts);
  buildOtherCategories();
  buildFooter();

  // 4. Init interactions
  initNavbar();
  initMobileMenu();
  initScrollReveal();
});

// =============================================
// META / HEAD
// =============================================
function buildMeta() {
  document.title = `${currentCategory.name} — ${SITE.brand.name}`;
  document.querySelector('meta[name="description"]').content =
    currentCategory.description;
}

// =============================================
// HERO BANNER
// =============================================
function buildHero() {
  const sec = document.getElementById('cat-hero');

  // Set background image
  if (currentCategory.image) {
    sec.style.background =
      `linear-gradient(to top, rgba(0,0,0,0.75) 0%, rgba(0,0,0,0.3) 50%, rgba(0,0,0,0.2) 100%),
       url('${currentCategory.image}') center/cover no-repeat`;
  }

  document.getElementById('bc-category').textContent  = currentCategory.name;
  document.getElementById('cat-hero-title').textContent = currentCategory.name;
  document.getElementById('cat-hero-desc').textContent  = currentCategory.description;
  document.querySelector('.brand-name').textContent    = SITE.brand.name;
}

// =============================================
// PRODUCTS GRID
// =============================================
function buildProducts(products) {
  const count = document.getElementById('products-count');
  count.textContent = `${products.length} products`;

  const grid = document.getElementById('products-grid');
  grid.innerHTML = products.map(p => `
    <div class="product-card" id="prod-${p.id}">
      <div class="product-img-wrap">
        <img
          src="${p.image}"
          alt="${p.name}"
          loading="lazy"
          onerror="this.src='images/${currentCategory.emoji ? '' : ''}cat-${currentCategory.id}.jpg'"
        />
        ${p.badge ? `<span class="product-badge badge-${p.badge.toLowerCase().replace(' ','')}">${p.badge}</span>` : ''}
        <div class="product-actions">
          <button onclick="enquire('${p.name}')">Enquire Now</button>
        </div>
      </div>
      <div class="product-body">
        <h3>${p.name}</h3>
        <p>${p.description}</p>
        <div class="product-price">
          <span class="price-current">${p.price}</span>
          ${p.originalPrice ? `<span class="price-original">${p.originalPrice}</span>` : ''}
          ${p.discount      ? `<span class="price-discount">${p.discount}</span>`      : ''}
        </div>
      </div>
    </div>
  `).join('');
}

// =============================================
// SORT
// =============================================
window.sortProducts = function(value) {
  let sorted = [...currentProducts];
  const parse = str => parseInt(str.replace(/[^0-9]/g, '')) || 0;

  if (value === 'price-asc')  sorted.sort((a,b) => parse(a.price) - parse(b.price));
  if (value === 'price-desc') sorted.sort((a,b) => parse(b.price) - parse(a.price));

  buildProducts(sorted);
  initScrollReveal();
};

// =============================================
// ENQUIRE (placeholder action)
// =============================================
window.enquire = function(name) {
  window.location.href = `index.html#contact`;
};

// =============================================
// OTHER CATEGORIES STRIP
// =============================================
function buildOtherCategories() {
  const others = SITE.categories.items.filter(c => c.id !== currentCategory.id);
  const grid   = document.getElementById('other-cats-grid');

  grid.innerHTML = others.map(c => `
    <a href="category.html?id=${c.id}" class="other-cat-chip">
      <img src="${c.image}" alt="${c.name}"
        onerror="this.parentElement.style.background='${c.gradient}';this.style.display='none'" />
      <div class="other-cat-chip-overlay">
        <span>${c.name}</span>
      </div>
    </a>
  `).join('');
}

// =============================================
// FOOTER
// =============================================
function buildFooter() {
  const F = SITE.footer;
  document.getElementById('footer-desc').textContent       = F.description;
  document.getElementById('footer-year').textContent       = F.copyrightYear;
  document.getElementById('footer-brand-name').textContent = SITE.brand.name;

  document.getElementById('footer-quick').innerHTML = F.quickLinks.map(l =>
    `<a href="index.html${l.link}">${l.text}</a>`).join('');

  document.getElementById('footer-cat').innerHTML = SITE.categories.items.slice(0, 4).map(c =>
    `<a href="category.html?id=${c.id}">${c.name}</a>`).join('');

  document.getElementById('footer-support').innerHTML = F.supportLinks.map(l =>
    `<a href="index.html${l.link}">${l.text}</a>`).join('');
}

// =============================================
// INTERACTIONS (same as app.js)
// =============================================
function initNavbar() {
  const navbar = document.getElementById('navbar');
  window.addEventListener('scroll', () => {
    // Always keep scrolled style on category page
    navbar.classList.add('scrolled');
  });
}

function initMobileMenu() {
  const hamburger  = document.getElementById('hamburger');
  const mobileMenu = document.getElementById('mobileMenu');
  hamburger.addEventListener('click', () => mobileMenu.classList.toggle('open'));
  document.addEventListener('click', e => {
    if (!hamburger.contains(e.target) && !mobileMenu.contains(e.target)) {
      mobileMenu.classList.remove('open');
    }
  });
}

window.closeMobile = () => document.getElementById('mobileMenu').classList.remove('open');

function initScrollReveal() {
  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry, i) => {
      if (entry.isIntersecting) {
        setTimeout(() => {
          entry.target.style.opacity    = '1';
          entry.target.style.transform  = 'translateY(0)';
        }, i * 60);
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.1 });

  document.querySelectorAll('.product-card, .other-cat-chip').forEach(el => {
    el.style.cssText += 'opacity:0;transform:translateY(20px);transition:opacity 0.5s ease,transform 0.5s ease;';
    observer.observe(el);
  });
}
